### 1. New payment
POST https://localhost:7092/api/Payments
Content-Type: application/json
baggage: customer.id=some_customer

{
  "expiryMonth": 11,
  "expiryYear": 2029,
  "currency": "GBP",
  "amount": 1050,
  "cvv": "123",
  "cardNumber": "5186001700008785"
}

> {%
    client.global.set("payment_id", response.body.id);
%}

### 2. Get payment
GET https://localhost:7092/api/Payments/{{payment_id}}
Accept: application/json

### 3. Rejection
POST https://localhost:7092/api/Payments
Content-Type: application/json
baggage: customer.id=some_customer

{
  "expiryMonth": 13,
  "expiryYear": 2029,
  "currency": "GBP",
  "amount": 1050,
  "cvv": "123",
  "cardNumber": "5186001700008785"
}
